scanner bot java docker origin
10dcar/scanner_bot pull request #1
Opened 2024-11-02 08:09 UTC by 10dcar

2024-11-11 17:23 UTC, Zeferin requested changes
You also added class files in git.
Please remove those.
Class files are automatically generated and they don't need to be saved in git.

2024-11-11 17:23 UTC, Zeferin commented on .idea/.gitignore
> +/workspace.xml
1.
.idea is a folder created and used by intelij IDE.
Usually, this is not commited in git. I would say you should remove it from commit and add the folder to .gitignore.

2. .gitignore files is wrongly placed. Please, move it in the root directory.

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/FortaLinuxJavaScannerBot.java
> +public class FortaLinuxJavaScannerBot extends TelegramLongPollingBot {
class rename sugestion: TelegramBot

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/FortaLinuxJavaScannerBot.java
> +            //jsonRedArr.forEach((s) ->System.out.println("key: " + s.getBotName() + " value " + s.getBotToken()));
remove leftover comment

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/FortaLinuxJavaScannerBot.java
> +        System.out.println("+++++++getBotUsername");
remove leftover print

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/FortaLinuxJavaScannerBot.java
> +        System.out.println("++++++++Am spus ceva");
remove leftover print

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/FortaLinuxJavaScannerBot.java
> +        System.out.println("+++++++getBotToken");
remove leftover print

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/FortaLinuxJavaScannerBot.java
> +            System.out.println("+++++++token::::" + botToken);
remove leftover print

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/FortaLinuxJavaScannerBot.java
> +        //citest datele despre
remove leftover comment

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/FortaLinuxJavaScannerBot.java
> +        //parul urmator: trebuie sa scot scorul din acest mesaj
remove leftover comment

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/HttpClientLocal.java
> +            //driver.findElement(By.className("aaa-name")).getText();
remove commented code

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/HttpClientLocal.java
> +            System.out.println("Status code: " + response.statusCode());
keep only usefull prints

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/JsonReader.java
> +        //System.out.println("---------Citit JSON bot data: " + botName + " " + botToken + " " + apiUrl);
remove leftover

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/JsonReader.java
> +        System.out.println("---------Citit JSON adrese: ");
remove leftover print

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/Main.java
> +        ApiContextInitializer.init();
remove leftover comment

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/Main.java
> +        primesc mesajul din telegram inregistrez NUMARUL cu care sunt apelat
remove this info and add it into README file

2024-11-11 17:23 UTC, Zeferin commented on src/main/java/Main.java
> +//citesc din json si din web
git repo is not suited for handling tasks. Better use Jira instead.
Remove this from repo and find a different place for management

2024-12-04 21:57 UTC, Zeferin requested changes

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientLocal.java
> +                .version(HttpClient.Version.HTTP_2)
HTTP v2 and HTTP v3 are really new and very interesting. 
For out app HTTP v1 is good enough, but, please, give yourself a minute to read about what (and when) was added in v2 and v3.

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientResponse.java
> +    //static String jsonPathName = "./src/main/resources/scannertest.json";
is this code comment usefull?

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientResponse.java
> +            //Object obj = new JSONParser().parse(this.body);
remove commented code. If you need to remember something from this you can take a note in README

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientResponse.java
> +    }
getScoreLocal and getScore contain mostly duplicated code. Please find another way to do the same thing without repeating yourself.

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/JsonReader.java
> +    //static String jsonPathName = "./src/main/resources/config.json";
leftover comment

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/JsonReader.java
> +            System.out.println("Current absolute path is: " + s);*/
leftover comment

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/JsonReader.java
> +        return ret;
this method always return an array of length 1. Why working with arrays when you always have exactly 1 entry?

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/JsonReader.java
> +        return ret;
some here, array has always have length 1

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/JsonReader.java
> +            }
why using a while when it always breaks at first iteration?

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/Main.java
> +        TelegramBotsApi botsApi = new TelegramBotsApi();
leftover comments

2024-12-04 21:57 UTC, Zeferin commented on src/main/java/bot/telegram/ScoreApi.java
> +}
this class only has 1 string and a getter. Better forget about this class and use the plain string directly

2024-12-05 21:07 UTC, 10dcar commented on src/main/java/bot/telegram/HttpClientResponse.java
> +    //static String jsonPathName = "./src/main/resources/scannertest.json";
for online docker server vs local server

2024-12-30 09:07 UTC, Zeferin requested changes

2024-12-30 09:07 UTC, Zeferin commented on Dockerfile
> +#COPY --from=build /app/src/main/resources /app/dependency
please, delete comments

2024-12-30 09:07 UTC, Zeferin commented on pom.xml
> +            <!-- <plugin>
please, delete comments

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/BotDataDefinition.java
> +}
This class includes two private fields and provides public getters and setters. I strongly recommend avoiding this design pattern. The constructor could be utilized to initialize the fields directly, eliminating the need for setter methods. For the getters, you could replace them with specialized methods that handle all the processing related to these two fields.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/Bot.java
> +}
Some of these methods are unused, and I don’t see any benefit in defining them—especially the getter and setter methods, which I generally don’t recommend using. According to a key coding principle, you should avoid implementing functionality that isn’t needed. Only 2 out of 9 defined methods are used.

The principle is called YAGNI (You Aren’t Gonna Need It). It advises against implementing features or code unless they are required, emphasizing simplicity and focusing only on what is necessary for the current functionality.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientData.java
> +}
Well done! You’ve correctly used the constructor here instead of relying on setter methods—this is a great practice to stick with. Now, consider whether you can optimize or replace the getter methods, perhaps by introducing specialized methods to handle specific logic (or completely deleting them if not used).

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientLocal.java
> +        };
Just a side note: here, you’re using what’s known as ‘anonymous classes.’ You’ve created two anonymous classes, as seen in the lines `new TrustManager` and `new X509TrustManager`, where you’re instantiating objects of anonymous types defined inline.

This could also be a great opportunity to explore the concept of anonymous methods and understand how they differ from anonymous classes.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientLocal.java
> +        }
Making exceptions silent without any form of handling or logging is generally not a good practice. It can lead to difficult-to-debug issues because it hides the root cause of potential problems. Instead, exceptions should be logged, handled appropriately, or at least documented to provide context.

Completely silencing an exception without justification should generally be avoided.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientLocal.java
> +    }
The logic in this method is too complex to maintain in a single method. It would be better to split it into separate methods: one dedicated to handling SSL certificates and another for managing the HTTP request. Moreover, avoid silently ignoring exceptions. Instead, log them appropriately, re-throw them if they represent critical failures, or provide a clear comment explaining why ignoring the exception is acceptable in this context.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientResponse.java
> +        System.out.println("Body: " + body);*/
remove comment

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientResponse.java
> +        this.body = body;
Great job! Once again, you’ve correctly used the constructor instead of defining setters. This time, it seems you’ve appropriately avoided using getters and instead defined specialized methods that work directly with the fields. Since the getter methods are not being used, please consider removing them to keep the code clean and focused.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/HttpClientResponse.java
> +                throw new RuntimeException(e);
Well done! Here, you’ve chosen not to silence the exception but instead rethrow it, which is a good practice for maintaining clarity and propagating errors appropriately.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/JsonReader.java
> +        jsonPathName = "./src/main/resources/config.json";
A good practice is to define string constants as global variables in a dedicated constants file and reference them wherever needed. This improves maintainability and reduces the risk of errors caused by hardcoding strings in multiple places.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/JsonReader.java
> +            BotDataDefinition objFortaStorj = objectMapper.readValue(new File(jsonPathName), BotDataDefinition.class);
I don’t see a clear benefit in keeping BotDataDefinition as a separate class. It might be more appropiate to move the logic from BotDataDefinition directly into JsonReader, simplifying the code and reducing unnecessary abstraction.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/JsonReader.java
> +    }
`readFortaBots ` and `readStorjBots` contain duplicated code. Let’s refactor this by extracting the shared logic into a reusable method or utility to adhere to the DRY (Don’t Repeat Yourself) principle.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/Main.java
> +        TelegramBot bot = new TelegramBot(jsonBots, localContentTest);
There doesn’t seem to be any benefit to passing new JsonReader() as the first parameter to the TelegramBot constructor. Could you remove this parameter from the constructor and refactor the code accordingly?

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/Main.java
> +        pa.periodicUpdate();
I would advise against using a dedicated class like PeriodicUpdate. It might be better to move its logic directly into this class to simplify the code and avoid unnecessary abstraction.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/ScannerAddress.java
> +}
Define a constructor and delete setter methods.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/ScannerDetails.java
> +public class ScannerDetails {
Please review the getters and setters in this class and consider applying the suggestions mentioned in my previous comments. Focus on reducing unnecessary methods and replacing them with more specialized logic where appropriate.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/StorjBot.java
> +    public StorjBot(String name, String address, String url, String token) {
I don't need you neeed the setters since the constructor is doing everything.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/TelegramBot.java
> +        this.send(this.getScore());
Lol, you’re making an additional HTTP request every time this.getScore() is called! It would be much better to fetch the value once, store the result, and reuse it instead of making the same request repeatedly. This will improve efficiency and reduce unnecessary network overhead.

2024-12-30 09:07 UTC, Zeferin commented on src/main/java/bot/telegram/TelegramBot.java
> +        }
These two for loops appear to be duplicated. Please refactor the code to eliminate the repetition and adhere to the DRY (Don’t Repeat Yourself) principle.

2024-12-30 09:07 UTC, Zeferin commented on src/main/resources/config.json
> +{
A binary file,` src/main/java/bot/telegram/forta_linux_scanner_bot_old.zip`, has been added to the Git repository. This should never happen under any circumstances. Please remove it from the repository and ensure such files are ignored by adding appropriate rules to the .gitignore file.

2025-02-15 10:50 UTC, Zeferin approved these changes

2025-02-15 10:54 UTC, merged